Update

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,29 @@
 #!/usr/bin/env bash
-#a Bash script that transfers a file from our client to a server
+#Bash script that transfers a file from our client to a server
 # By: Zakaria ELORCHE
 
-if [ $# -lt 4 ]
+# Vérifie si tous les paramètres nécessaires sont fournis
+if [ "$#" -lt 4 ]
 then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
+
+# parameters to variables
+PATH_TO_FILE=$1
+IP=$2
+USERNAME=$3
+PATH_TO_SSH_KEY=$4
+
+# Effectue le transfert du fichier en utilisant scp
+scp -o "StrictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+
+#checking if the transfert was good
+if [ $? -eq 0 ]
+then
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
+else
+	echo "FILE TRANSFER FAILED"
+fi
+
+
